# Generated by Django 3.1 on 2020-10-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='banner',
            field=models.ImageField(null=True, upload_to='banner/'),
        ),
    ]
