# Generated by Django 3.0.8 on 2020-10-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rankData',
            field=models.IntegerField(null=True),
        ),
    ]
