# Generated by Django 3.1 on 2020-08-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20200811_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['nickname']},
        ),
    ]
