# Generated by Django 3.0.8 on 2020-10-17 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0003_auto_20201015_1533'),
        ('usermanagement', '0002_auto_20201015_1550'),
    ]

    operations = [
    ]
