# Generated by Django 3.1 on 2020-10-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201005_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bidPrice',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='sellPrice',
            field=models.IntegerField(default=-1),
        ),
    ]
