# Generated by Django 3.1 on 2020-08-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
