# Generated by Django 3.1 on 2020-08-17 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote',
        ),
    ]
