# Generated by Django 3.1 on 2020-08-18 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20200818_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='down',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='up',
        ),
        migrations.RemoveField(
            model_name='like',
            name='down',
        ),
        migrations.RemoveField(
            model_name='like',
            name='up',
        ),
    ]
