<<<<<<< HEAD
# Generated by Django 3.0.8 on 2020-10-27 06:02
=======
# Generated by Django 3.0.8 on 2020-10-28 05:43
>>>>>>> f92e4b81859464bb975267387d587588bee8b911

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.CharField(max_length=1000)),
            ],
        ),
    ]
