# Generated by Django 3.1 on 2020-08-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='postid',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='uid',
        ),
    ]
