# Generated by Django 3.1 on 2020-08-19 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200819_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='postid',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='uid',
            new_name='user',
        ),
    ]
