# Generated by Django 3.1 on 2020-08-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20200819_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='contents',
        ),
    ]
