# Generated by Django 3.0.8 on 2020-11-13 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dearbornapps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidinfo',
            name='post',
        ),
        migrations.RemoveField(
            model_name='bidinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bidPrice',
        ),
        migrations.RemoveField(
            model_name='post',
            name='expire_dt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_repo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sell',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sellPrice',
        ),
        migrations.DeleteModel(
            name='Assess',
        ),
        migrations.DeleteModel(
            name='BidInfo',
        ),
    ]
