# Generated by Django 3.0.8 on 2020-11-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dearbornapps', '0002_auto_20201113_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
