# Generated by Django 3.0.8 on 2020-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dearbornapps', '0002_message_isread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='updated_dt',
            field=models.DateField(auto_now_add=True),
        ),
    ]
