# Generated by Django 3.0.8 on 2020-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dearbornapps', '0003_auto_20201119_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='updated_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
