<<<<<<< HEAD
# Generated by Django 3.1 on 2020-10-05 11:59

from django.db import migrations, models
=======
# Generated by Django 3.1 on 2020-10-13 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 23c59bc8dcbabca84ecc23cc277c13995ce8d80d


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 23c59bc8dcbabca84ecc23cc277c13995ce8d80d
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000)),
                ('updated_dt', models.TimeField(auto_now_add=True)),
<<<<<<< HEAD
=======
                ('userFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From', to=settings.AUTH_USER_MODEL)),
                ('userTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To', to=settings.AUTH_USER_MODEL)),
>>>>>>> 23c59bc8dcbabca84ecc23cc277c13995ce8d80d
            ],
        ),
    ]
