<<<<<<< HEAD
# Generated by Django 3.1 on 2020-10-05 11:59

from django.db import migrations, models
=======
# Generated by Django 3.1 on 2020-10-13 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 23c59bc8dcbabca84ecc23cc277c13995ce8d80d


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('post', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 23c59bc8dcbabca84ecc23cc277c13995ce8d80d
    ]

    operations = [
        migrations.CreateModel(
            name='Assess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.FloatField(default=0)),
                ('color', models.FloatField(default=0)),
                ('individuality', models.FloatField(default=0)),
                ('practicality', models.FloatField(default=0)),
                ('trend', models.FloatField(default=0)),
<<<<<<< HEAD
=======
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
>>>>>>> 23c59bc8dcbabca84ecc23cc277c13995ce8d80d
            ],
        ),
    ]
