export const getCategoryName = (category) => {
    switch(category){
        case 0: return "메인"
        case 1: return "남성 상의"
        case 2: return "남성 하의"
        case 3: return "남성 아우터"
        case 4: return "남성 속옷"
        case 5: return "상의"
        case 6: return "하의"
        case 7: return "원피스"
        case 8: return "아우터"
        case 9: return "속옷"
        case 10: return "귀걸이"
        case 11: return "시계"
        case 12: return "목걸이"
        case 13: return "팔찌"
        case 14: return "발찌"
        case 15: return "안경"
        case 16: return "반지"
        case 17: return "모자"
        case 18: return "단화"
        case 19: return "스포츠"
        case 20: return "슬리퍼"
        case 21: return "샌들"
        case 22: return "하이힐"
        default: return ""
    }
}